---
name: macOS

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    env:
      COLORTERM: truecolor
      NPROC: 2
      TERM: xterm
    name: üçé build, test, & install
    runs-on: macos-latest

    steps:

      - name: "Install tools and libraries via Homebrew"
        run: |
          brew install \
            coreutils \
            doctest \
            ffmpeg \
            libunistring \
            ncurses \
            pandoc \
            readline \
            rust

      - name: "notcurses: checkout"
        uses: actions/checkout@v2
        with:
          repository: dankamongmen/notcurses
          path: notcurses
          fetch-depth: 0

      - name: "notcurses: cmake"
        run: |
          cd notcurses
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release

      - name: "notcurses: make"
        run: |
          cd notcurses/build
          make -j${NPROC}

      # - name: ctest
      #   run: |
      #     cd build
      #     ctest --output-on-failure

      - name: "notcurses: make install"
        run: |
          cd notcurses/build
          sudo make install

      - name: "ü¶Ä libnotcurses-sys: checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "ü¶Ä libnotcurses-sys: build"
        run: |
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
          rustc --version
          rustup override set 1.54 # MSRV
          rustc --version
          cargo build

      - name: "ü¶Ä libnotcurses-sys: test"
        run: |
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
          rustc --version
          cargo t_all
