---
name: Ubuntu

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    env:
      COLORTERM: truecolor
      NPROC: 2
      TERM: xterm
    name: üêß build, test, & install
    runs-on: ubuntu-latest

    steps:
      - name: "notcurses: Install tools and libraries via APT"
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            doctest-dev \
            ffmpeg \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libncurses-dev \
            libqrcodegen-dev \
            libreadline-dev \
            libswscale-dev \
            libunistring-dev \
            pkg-config

      - name: "notcurses: checkout"
        uses: actions/checkout@v2
        with:
          repository: dankamongmen/notcurses
          path: notcurses
          fetch-depth: 0

      - name: "notcurses: cmake"
        run: |
          cd notcurses
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DUSE_PANDOC=OFF \
            -DUSE_QRCODEGEN=on

      - name: "notcurses: make"
        run: |
          cd notcurses/build
          make -j${NPROC}

      # - name: "ctest"
      #   run: |
      #     cd notcurses/build
      #     ctest --output-on-failure

      - name: "notcurses: make install"
        run: |
          cd notcurses/build
          sudo make install
          sudo ldconfig

      - name: "ü¶Ä libnotcurses-sys: checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "ü¶Ä libnotcurses-sys: build the Rust wrappers"
        run: |
          rustc --version
          rustup override set 1.56 # MSRV
          rustc --version
          cargo build # --verbose
          cargo t_all
